#!/usr/bin/env python3
"""Rasterize DejaVu Sans into the checked-in Kernel1 Sans ASCII atlas (Pillow).

Usage: python tools/generate_ui_font.py /path/to/DejaVuSans.ttf
Normal kernel builds do not need Pillow or the source font.
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype(sys.argv[1], 14)
width, height = 16, 18
rows = []
advances = []
for code in range(32, 127):
    glyph = chr(code)
    canvas = Image.new("L", (width, height))
    ImageDraw.Draw(canvas).text((0, 0), glyph, font=font, fill=255)
    values = [round(value / 17) for value in canvas.getdata()]
    packed = [values[i] << 4 | values[i + 1] for i in range(0, len(values), 2)]
    rows.append("    {" + ",".join(f"0x{value:02x}" for value in packed) + "}")
    advances.append(str(round(font.getlength(glyph))))
output = Path(__file__).resolve().parents[1] / "kernel/core/ui_font.h"
output.write_text(
    "/* Generated by tools/generate_ui_font.py. Kernel1 Sans, derived from DejaVu Sans.\n"
    " * License: docs/licenses/DejaVu.txt. 4-bit coverage, 16 x 18 pixels. */\n"
    "#ifndef KERNEL_UI_FONT_H\n#define KERNEL_UI_FONT_H\n"
    "static const unsigned char ui_font_advance[95] = {" + ",".join(advances) + "};\n"
    "static const unsigned char ui_font_pixels[95][144] = {\n" + ",\n".join(rows) +
    "\n};\n#endif\n", encoding="ascii")
print(f"Generated {output}: {95 * 144 + 95} bytes of font data")
